services:
  - type: web
    name: create-schematic-dependency-checker
    env: docker
    plan: free           # optional: or "starter" / "pro" if upgrading
    dockerfilePath: ./Dockerfile
    autoDeploy: true     # automatically redeploys on git push
    envVars:
      - key: PORT
        value: 8080      # matches the EXPOSE in Dockerfile
