spring:
  application:
    name: create-schematic-dependency-checker
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB


server:
  port: 8080
  error:
    include-message: always
    whitelabel:
      enabled: false


logging:
  level:
    root: INFO
    com.example: DEBUG

